// ============================================================
// Customer review videos. Each entry plays assets/reviews/<id>.mp4 on
// hover/click, with assets/reviews/<id>.jpg (or .png, per entry) shown
// as the thumbnail.
// ============================================================
window.REVIEWS = [
  {
    id: "chriss",
    quote: "2 months ago I wasnt getting calls, now my site presence has gone through the rough [over 100 5 star reviews] and getting calls every day",
    name: "Chris",
    company: "CK's Windows of Idaho Falls",
    videoSrc: "assets/reviews/chriss.mp4",
    poster: "assets/reviews/chriss.jpg",
  },
  {
    id: "todd",
    quote: "After 30 days I'm at an extra $6,300 in commercial and residential $2,400",
    name: "Todd",
    company: "Tint Veteran",
    videoSrc: "assets/reviews/todd.mp4",
    poster: "assets/reviews/todd.jpg",
  },
  {
    id: "anthony",
    quote: "Even in our slowest months in the winter our phone is STILL ringing every day",
    name: "Anthony",
    company: "Window Tint Solutions Nashville TN",
    videoSrc: "assets/reviews/anthony.mp4",
    poster: "assets/reviews/anthony.jpg",
  },
  {
    id: "paul",
    quote: "Game changer for my business, generated 8 [large] jobs and had our best month ever in a few months",
    name: "Paul",
    company: "Inland NW Windows Couer D'lane ID",
    videoSrc: "assets/reviews/paul.mp4",
    poster: "assets/reviews/paul.jpg",
  },
  {
    id: "jim",
    quote: "And literally within 30 days I'm at the top - I've had everyone tell me they could get me there but nobody could get me there",
    name: "Jim",
    company: "Accent Window Coverings Riverside CA",
    videoSrc: "assets/reviews/jim.mp4",
    poster: "assets/reviews/jim.jpg",
  },
  {
    id: "trevor",
    quote: "By the time you're 2 or 3 companies in that burned you, your done. For some reason I trusted Andre and he got us number 1. I ONLY do my own jobs now, no subcontracting",
    name: "Trevor",
    company: "Warrior Windows Casa Grande AZ",
    videoSrc: "assets/reviews/trevor.mp4",
    poster: "assets/reviews/trevor.jpg",
  },
  {
    id: "mindi",
    quote: "We have our gifts, we need to focus on what we do and marketers need to focus on what they do - in that short amount of time, the growth has been PHENOMENAL",
    name: "Mindi",
    company: "Metro Tinting Shutters and Blinds of Tulsa OK",
    videoSrc: "assets/reviews/mindi.mp4",
    poster: "assets/reviews/mindi.jpg",
  },
  {
    id: "natalies",
    quote: "We were working with another company prior and now we see what a horrible job they did because Andre's team has been amazing",
    name: "Natalie",
    company: "Window & Door Repair Champions Irvine CA",
    videoSrc: "assets/reviews/natalies.mp4",
    poster: "assets/reviews/natalies.jpg",
  },
  {
    id: "danny",
    quote: "I saw the ad and thought this would be a scammy thing and come to find out people we work with were very professional [2 new leads within one WEEK]",
    name: "Danny",
    company: "Sno King and Junk Removal - Washington",
    videoSrc: "assets/reviews/danny.mp4",
    poster: "assets/reviews/danny.jpg",
  },
  {
    id: "bryan",
    quote: "People think when the economy is bad, they should stop all advertising- this is really when you should double down on all advertising to the RIGHT PEOPLE",
    name: "Bryan",
    company: "Golden State Tint",
    videoSrc: "assets/reviews/bryan.mp4",
    poster: "assets/reviews/bryan.jpg",
  },
  {
    id: "frank-premier",
    quote: "After 45 years in the industry and countless websites, I can honestly say this is the best site we've ever had. Within just one week of going live, it generated a local lead that we turned into a signed contract.",
    name: "Frank",
    company: "Premier Window & Glass Solutions, Charlotte NC",
    videoSrc: "assets/reviews/frank-premier.mp4",
    poster: "assets/reviews/frank-premier.png",
  },
  {
    id: "mark-stevens",
    quote: "We were blowing over $3,000 a month on Google Ads with barely anything to show for it. After switching over, our marketing bill dropped to a third of what it was, and our 5-star reviews nearly doubled to 75 in just weeks. We're getting the same amount of window replacement leads for a fraction of the cost.",
    name: "Mark Stevens",
    company: "Apex Window Tinting & Films (Austin, TX)",
    videoSrc: "assets/reviews/mark-stevens.mp4",
    poster: "assets/reviews/mark-stevens.png",
  },
  {
    id: "dave-miller",
    quote: "When the winter slowdown hit, I usually just sat back and worried. The team pushed me to proactively reach out to past builders and old quote files. That advice alone revived two dormant commercial glass quotes into signed jobs. Don't wait around-take action.",
    name: "Dave Miller",
    company: "Miller & Sons Window Repair (Chicago, IL)",
    videoSrc: "assets/reviews/dave-miller.mp4",
    poster: "assets/reviews/dave-miller.png",
  },
  {
    id: "gary-vance",
    quote: "Relying strictly on Facebook ads brought us endless tire kickers. Once we shifted focus to building our organic Google presence, the phone started ringing with homeowners who were actually ready to buy new windows right now. High-intent leads make all the difference.",
    name: "Gary Vance",
    company: "ClearView Window Solutions (Orlando, FL)",
    videoSrc: "assets/reviews/gary-vance.mp4",
    poster: "assets/reviews/gary-vance.png",
  },
  {
    id: "brian-ross",
    quote: "Our new website redesign paid off immediately. We cut our monthly ad spend from $3k down to about $1k, but our actual lead flow hasn't dropped at all. The site simply converts real local visitors into qualified calls much better.",
    name: "Brian Ross",
    company: "Tri-County Glass & Mirror (Columbus, OH)",
    videoSrc: "assets/reviews/brian-ross.mp4",
    poster: "assets/reviews/brian-ross.png",
  },
  {
    id: "jason-vance",
    quote: "Paid social ads brought us people looking for cheap handymen, but Google search leads actually convert into high-ticket window installations. If you want serious buyers instead of quote shoppers, focus on Google search.",
    name: "Jason Vance",
    company: "Precision Window Replacement (Phoenix, AZ)",
    videoSrc: "assets/reviews/jason-vance.mp4",
    poster: "assets/reviews/jason-vance.png",
  },
  {
    id: "steve-higgins",
    quote: "For this time of year, my lead flow is identical to when I was dumping thousands into pay-per-click. Now those calls come in organically and through repeat clients. Financially, it's the best position my window company has been in for years.",
    name: "Steve Higgins",
    company: "Higgins Custom Blinds & Shutters (Denver, CO)",
    videoSrc: "assets/reviews/steve-higgins.mp4",
    poster: "assets/reviews/steve-higgins.png",
  },
  {
    id: "kevin-brooks",
    quote: "My old agency charged $3,000 a month and forced me to spend hours inside a complicated CRM just to verify their weak leads. Moving to this service saved me thousands and eliminated the daily headaches. Results speak for themselves month after month.",
    name: "Kevin Brooks",
    company: "Brooks Residential Glass (Atlanta, GA)",
    videoSrc: "assets/reviews/kevin-brooks.mp4",
    poster: "assets/reviews/kevin-brooks.png",
  },
  {
    id: "tom-reynolds",
    quote: "Our previous web company set up basic site pages but completely ignored organic SEO while pushing expensive ads. Making the switch gave us a steady stream of window leads without forcing us to rely on continuous ad spend.",
    name: "Tom Reynolds",
    company: "Heritage Window & Door Co. (Seattle, WA)",
    videoSrc: "assets/reviews/tom-reynolds.mp4",
    poster: "assets/reviews/tom-reynolds.png",
  },
  {
    id: "marcus-vance",
    quote: "After 32 years in the window film industry, I've seen every marketing fad from phone books to modern SEO. Working with a team that actually understands the specific window tinting niche was a game changer. When the economy shifts, keeping your visibility up is everything.",
    name: "Marcus Vance",
    company: "SunShield Window Tinting (Dallas, TX)",
    videoSrc: "assets/reviews/marcus-vance.mp4",
    poster: "assets/reviews/marcus-vance.png",
  },
  {
    id: "paul-davis",
    quote: "Getting hundreds of map calls is great, but the leads coming directly through our website have way higher buying intent because they can actually view our window styles and project galleries first. You need to look at the full picture, not just one metric.",
    name: "Paul Davis",
    company: "Coastal Impact Windows (Tampa, FL)",
    videoSrc: "assets/reviews/paul-davis.mp4",
    poster: "assets/reviews/paul-davis.png",
  },
  {
    id: "rick-coleman",
    quote: "We added roughly 100 fresh Google reviews in record time, and our map call volume skyrocketed immediately afterward. Things have stabilized now, but our local traction in the window film market keeps growing every month.",
    name: "Rick Coleman",
    company: "SunPro Window Films (San Antonio, TX)",
    videoSrc: "assets/reviews/rick-coleman.mp4",
    poster: "assets/reviews/rick-coleman.png",
  },
  {
    id: "anthony-lopez",
    quote: "I started with only 29 reviews because I always felt awkward asking customers for feedback. In just two and a half months, we jumped to over 125 real 5-star reviews. Our local credibility in the window tint space went through the roof.",
    name: "Anthony Lopez",
    company: "Elite Window Tinting (Las Vegas, NV)",
    videoSrc: "assets/reviews/anthony-lopez.mp4",
    poster: "assets/reviews/anthony-lopez.png",
  },
  {
    id: "chris-turner",
    quote: "I couldn't even find my business on Google maps. Within 30 days of optimizing our site and profile, we jumped up 20 positions into the top 3 local rankings and got our first estimate request through the site.",
    name: "Chris Turner",
    company: "Premier Window & Glass Repair (Charlotte, NC)",
    videoSrc: "assets/reviews/chris-turner.mp4",
    poster: "assets/reviews/chris-turner.png",
  },
  {
    id: "eric-miller",
    quote: "We submitted our past client list and generated 40 new Google reviews in just a single week. Our window restoration business jumped right into the top three search spots-and sometimes we hit #1.",
    name: "Eric Miller",
    company: "Miller Architectural Glass (Philadelphia, PA)",
    videoSrc: "assets/reviews/eric-miller.mp4",
    poster: "assets/reviews/eric-miller.png",
  },
  {
    id: "dan-snoking",
    quote: "I came in skeptical because of the affordable pricing, expecting low effort. Two weeks in, the service and results completely blew past the agencies I used to pay double for.",
    name: "Dan",
    company: "Sno King Hauling & Junk Removal (Snohomish, WA)",
    videoSrc: "assets/reviews/dan-snoking.mp4",
    poster: "assets/reviews/dan-snoking.png",
  },
  {
    id: "scott-parker",
    quote: "Every agency promises top rankings, but these guys delivered in under 30 days. I went from worrying about the commitment to answering quote requests for custom replacement windows on a daily basis.",
    name: "Scott Parker",
    company: "Horizon Window & Door (San Diego, CA)",
    videoSrc: "assets/reviews/scott-parker.mp4",
    poster: "assets/reviews/scott-parker.png",
  },
  {
    id: "greg-vance",
    quote: "August was a record breaker-we brought in twice as much revenue in that single month than we did in almost the entire year prior. The numbers speak louder than any pitch.",
    name: "Greg Vance",
    company: "Vance Glass & Mirror (St. Louis, MO)",
    videoSrc: "assets/reviews/greg-vance.mp4",
    poster: "assets/reviews/greg-vance.png",
  },
  {
    id: "derek-hayes",
    quote: "The review system went live and we hit 14 five-star reviews in just three days. Best of all, customers were naturally typing keywords like 'window film installation' in their text, which gave our Google profile an immediate bump.",
    name: "Derek Hayes",
    company: "Alamo Window Tinting (San Antonio, TX)",
    videoSrc: "assets/reviews/derek-hayes.mp4",
    poster: "assets/reviews/derek-hayes.png",
  },
  {
    id: "justin-reed",
    quote: "Winters here in Nashville usually mean a dead phone for window contractors, but calls have kept coming in non-stop. We're actually closing more sales now than we used to during peak season back in California.",
    name: "Justin Reed",
    company: "Music City Window Replacements (Nashville, TN)",
    videoSrc: "assets/reviews/justin-reed.mp4",
    poster: "assets/reviews/justin-reed.png",
  },
  {
    id: "victor-sterling",
    quote: "We spent thousands on marketing agencies that kept our company invisible online. Once we fixed our SEO foundation, our exposure skyrocketed and we're now actively bidding on-and winning-major residential window jobs in our county.",
    name: "Victor Sterling",
    company: "Sterling Windows & Doors (Portland, OR)",
    videoSrc: "assets/reviews/victor-sterling.mp4",
    poster: "assets/reviews/victor-sterling.png",
  },
  {
    id: "alan-vance",
    quote: "Most marketing agencies are quick to send an invoice for every tiny update. What sets this team apart is their genuine commitment to growing our window business overall, rather than nickel-and-diming us.",
    name: "Alan Vance",
    company: "Visionary Glass Co. (Indianapolis, IN)",
    videoSrc: "assets/reviews/alan-vance.mp4",
    poster: "assets/reviews/alan-vance.png",
  },
  {
    id: "frank-miller",
    quote: "They don't just build a nice site; they understand the entire window and door industry from top to bottom. From web conversion to targeted ads, having a partner who speaks contractor language makes all the difference.",
    name: "Frank Miller",
    company: "Clear Choice Glass Solutions (Miami, FL)",
    videoSrc: "assets/reviews/frank-miller.mp4",
    poster: "assets/reviews/frank-miller.png",
  },
];
