// ============================================================
// Customer review videos. Each entry plays assets/reviews/<id>.mp4 on
// hover/click, with assets/reviews/<id>.jpg shown as the thumbnail.
// ============================================================
window.REVIEWS = [
  {
    id: "chriss",
    quote: "2 months ago I wasnt getting calls, now my site presence has gone through the rough [over 100 5 star reviews] and getting calls every day",
    name: "Chris",
    company: "CK's Windows of Idaho Falls",
    videoSrc: "assets/reviews/chriss.mp4",
    poster: "assets/reviews/chriss.jpg",
  },
  {
    id: "todd",
    quote: "After 30 days I'm at an extra $6,300 in commercial and residential $2,400",
    name: "Todd",
    company: "Tint Veteran",
    videoSrc: "assets/reviews/todd.mp4",
    poster: "assets/reviews/todd.jpg",
  },
  {
    id: "anthony",
    quote: "Even in our slowest months in the winter our phone is STILL ringing every day",
    name: "Anthony",
    company: "Window Tint Solutions Nashville TN",
    videoSrc: "assets/reviews/anthony.mp4",
    poster: "assets/reviews/anthony.jpg",
  },
  {
    id: "paul",
    quote: "Game changer for my business, generated 8 [large] jobs and had our best month ever in a few months",
    name: "Paul",
    company: "Inland NW Windows Couer D'lane ID",
    videoSrc: "assets/reviews/paul.mp4",
    poster: "assets/reviews/paul.jpg",
  },
  {
    id: "jim",
    quote: "And literally within 30 days I'm at the top - I've had everyone tell me they could get me there but nobody could get me there",
    name: "Jim",
    company: "Accent Window Coverings Riverside CA",
    videoSrc: "assets/reviews/jim.mp4",
    poster: "assets/reviews/jim.jpg",
  },
  {
    id: "trevor",
    quote: "By the time you're 2 or 3 companies in that burned you, your done. For some reason I trusted Andre and he got us number 1. I ONLY do my own jobs now, no subcontracting",
    name: "Trevor",
    company: "Warrior Windows Casa Grande AZ",
    videoSrc: "assets/reviews/trevor.mp4",
    poster: "assets/reviews/trevor.jpg",
  },
  {
    id: "mindi",
    quote: "We have our gifts, we need to focus on what we do and marketers need to focus on what they do - in that short amount of time, the growth has been PHENOMENAL",
    name: "Mindi",
    company: "Metro Tinting Shutters and Blinds of Tulsa OK",
    videoSrc: "assets/reviews/mindi.mp4",
    poster: "assets/reviews/mindi.jpg",
  },
  {
    id: "natalies",
    quote: "We were working with another company prior and now we see what a horrible job they did because Andre's team has been amazing",
    name: "Natalie",
    company: "Window & Door Repair Champions Irvine CA",
    videoSrc: "assets/reviews/natalies.mp4",
    poster: "assets/reviews/natalies.jpg",
  },
  {
    id: "danny",
    quote: "I saw the ad and thought this would be a scammy thing and come to find out people we work with were very professional [2 new leads within one WEEK]",
    name: "Danny",
    company: "Sno King and Junk Removal - Washington",
    videoSrc: "assets/reviews/danny.mp4",
    poster: "assets/reviews/danny.jpg",
  },
  {
    id: "bryan",
    quote: "People think when the economy is bad, they should stop all advertising- this is really when you should double down on all advertising to the RIGHT PEOPLE",
    name: "Bryan",
    company: "Golden State Tint",
    videoSrc: "assets/reviews/bryan.mp4",
    poster: "assets/reviews/bryan.jpg",
  },
];
